version: '3.8'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Jakarta
    volumes:
      - ~/.n8n:/home/node/.n8n
    restart: unless-stopped
